### ISSUE TITLE
elm 0.16 support

### ISSUE THREAD

**Issue by berndca** [rtfeldman/grunt-elm#9]
Do you have any plans to support elm 0.16?

I'm getting the following error messages, even though elm make works fine.

> > Detected errors in 2 modules.
> > ## ERRORS in dependency elm-lang/core 3.0.0
> > 
> > This error probably means that the 'elm-lang/core' has some
> > package constraint that is too permissive. You should definitely inform the
> > maintainer to get this fixed and save other people from this pain.
> > 
> > In the meantime, you can attempt to artificially constrain things by adding
> > some extra constraints to your elm-package.json though that is not
> > the long term solution.
> > ## ERRORS in dependency elm-lang/core 3.0.0
> > 
> > This error probably means that the 'elm-lang/core' has some
> > package constraint that is too permissive. You should definitely inform the
> > maintainer to get this fixed and save other people from this pain.
> > 
> > In the meantime, you can attempt to artificially constrain things by adding
> > some extra constraints to your elm-package.json though that is not
> > the long term solution.

Thanks, Bernd

**Comment by grempe** [comment]
:+1:

**Comment by splodingsocks** [comment]
I'm seeing this too, as of this morning. Any idea what's going on, Richard?

**Comment by rtfeldman** [comment]
Fixed by https://github.com/rtfeldman/grunt-elm/pull/13
